In [ ]:
# importamos numpy 
import numpy as np


In [20]:
# Creamos array o arreglo 

# Crear una array de una dimensión 
array_unidim = np.array([1,2,3,4,5]) 

# Creamos un array de 2 dimensiones de 2 x 3 (filas x columnas)
array_bidim = np.array([[1,2,3],
                        [4,5,6]])

# Creamos un array de 3 dimensiones 
array_tridim = np.array([
                        [[1,2,3],[4,5,6]],
                        [[7,8,9],[10,11,12]]
                        ])

# Visualizamos nuestros array
print("----------------------")
print(array_unidim)
print("----------------------")
print(array_bidim)
print("----------------------")
print(array_tridim)
print("----------------------")

----------------------
[1 2 3 4 5]
----------------------
[[1 2 3]
 [4 5 6]]
----------------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
----------------------


# Obtenemos propiedades de neustros array 
- array_unidim.shape # nos die el numero de elementos en su lista
- array_unidim.ndim # nimero de dimensiones 
- array_unidim.dtype # que tipos de datos hay en el array
- array_unidim.size # su tamaño 

In [ ]:
# Obtenemos propiedades de neustros array 
array_unidim.shape, array_unidim.ndim, array_unidim.dtype,array_unidim.size

# vemos que es de 5 de ancho, 1 sola dimensión, tipo int64 y tiene 5 elementos 


((5,), 1, dtype('int64'), 5)

In [ ]:
array_bidim.shape, array_bidim.ndim, array_bidim.dtype,array_bidim.size 

# vemos que es de 2 filas por 3 columnas, 2 dimensiones , tipo de dato int64  y tiene 6 elementos 

((2, 3), 2, dtype('int64'), 6)

In [ ]:
array_tridim.shape, array_tridim.ndim, array_tridim.dtype,array_tridim.size 

# Vemos que tiene 2 tablas con 2 filas y 3 columnas cada tabla, 3 dimensiones, tipo de dato int64 y tiene 12 elementos

((2, 2, 3), 3, dtype('int64'), 12)

# Vemos similitudes con Pandas

In [11]:
# importamos pandas 
import pandas as pd

In [ ]:
# Cremos un daraframe con pandas el cual nos estructurara los datos 
datos = pd.DataFrame(array_bidim)
datos

0  1  2
0  1  2  3
1  4  5  6

# Volvemos a trabjar con numpy

In [21]:
# Creamos un array de 4 filas por 3 columnas de manera rapida con ".ones" pero se hara de puros numeros 1
unos = np.ones((4,3))
unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
# Creamos un array de 2 tablas con 4 filas por 3 columnas formada unicamente con ceros 
cero = np.zeros((2,4,3))
cero

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [23]:
# Creamos un array con con numeros del 0 al 100, saltando de 5 en 5 
array_1 = np.arange(0,100,5)
array_1

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [26]:
# Cramos un array de números aleatorios enteros comprendidos entre 0 y 10, de tamañao 2 filas por 5 columnas (2x5)
array_2 = np.random.randint(0,10,(2,5))
array_2

array([[6, 0, 3, 8, 0],
       [1, 8, 3, 3, 0]], dtype=int32)

In [28]:
# creamos un array de numeros aletorios pero con punto decimal con "random" pero solo entre 0 y 1
array_3 = np.random.random((3,5))
array_3 

array([[0.77308219, 0.77038392, 0.46980311, 0.4295424 , 0.44430935],
       [0.36451598, 0.63167168, 0.982812  , 0.75886702, 0.12615849],
       [0.38109733, 0.25695448, 0.85027155, 0.93684444, 0.44654857]])

In [ ]:
# Establecemos una semilla de numeros aleatorios, cada semilla tiene una secuencia de numeros aleatorios fijos ,
# por ello fijar una semillia hebita que la aleetoriedad se repita cambie

np.random.seed(30)

# Creamos un array de números aleatorios enntre 0 y 10 de tamaño (3,5)
array_4 =np.random.randint(0,10,(3,5))
array_4

array([[5, 5, 4, 7, 2],
       [5, 1, 3, 9, 7],
       [7, 1, 1, 3, 2]], dtype=int32)