In [4]:
# importamos numpy 
import numpy as np


In [5]:
# Creamos array o arreglo 

# Crear una array de una dimensión 
array_unidim = np.array([1,2,3,4,5]) 

# Creamos un array de 2 dimensiones de 2 x 3 (filas x columnas)
array_bidim = np.array([[1,2,3],
                        [4,5,6]])

# Creamos un array de 3 dimensiones 
array_tridim = np.array([
                        [[1,2,3],[4,5,6]],
                        [[7,8,9],[10,11,12]]
                        ])

# Visualizamos nuestros array
print("----------------------")
print(array_unidim)
print("----------------------")
print(array_bidim)
print("----------------------")
print(array_tridim)
print("----------------------")

----------------------
[1 2 3 4 5]
----------------------
[[1 2 3]
 [4 5 6]]
----------------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
----------------------


# Obtenemos propiedades de neustros array 
- array_unidim.shape # nos die el numero de elementos en su lista
- array_unidim.ndim # nimero de dimensiones 
- array_unidim.dtype # que tipos de datos hay en el array
- array_unidim.size # su tamaño 

In [6]:
# Obtenemos propiedades de neustros array 
array_unidim.shape, array_unidim.ndim, array_unidim.dtype,array_unidim.size

# vemos que es de 5 de ancho, 1 sola dimensión, tipo int64 y tiene 5 elementos 


((5,), 1, dtype('int64'), 5)

In [7]:
array_bidim.shape, array_bidim.ndim, array_bidim.dtype,array_bidim.size 

# vemos que es de 2 filas por 3 columnas, 2 dimensiones , tipo de dato int64  y tiene 6 elementos 

((2, 3), 2, dtype('int64'), 6)

In [8]:
array_tridim.shape, array_tridim.ndim, array_tridim.dtype,array_tridim.size 

# Vemos que tiene 2 tablas con 2 filas y 3 columnas cada tabla, 3 dimensiones, tipo de dato int64 y tiene 12 elementos

((2, 2, 3), 3, dtype('int64'), 12)

# Vemos similitudes con Pandas

In [9]:
# importamos pandas 
import pandas as pd

In [10]:
# Cremos un daraframe con pandas el cual nos estructurara los datos 
datos = pd.DataFrame(array_bidim)
datos

0  1  2
0  1  2  3
1  4  5  6

# Volvemos a trabjar con numpy

In [11]:
# Creamos un array de 4 filas por 3 columnas de manera rapida con ".ones" pero se hara de puros numeros 1
unos = np.ones((4,3))
unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# Creamos un array de 2 tablas con 4 filas por 3 columnas formada unicamente con ceros 
cero = np.zeros((2,4,3))
cero

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
# Creamos un array con con numeros del 0 al 100, saltando de 5 en 5 
array_1 = np.arange(0,100,5)
array_1

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [14]:
# Cramos un array de números aleatorios enteros comprendidos entre 0 y 10, de tamañao 2 filas por 5 columnas (2x5)
array_2 = np.random.randint(0,10,(2,5))
array_2

array([[6, 4, 8, 5, 8],
       [8, 4, 0, 5, 9]], dtype=int32)

In [15]:
# creamos un array de numeros aletorios pero con punto decimal con "random" pero solo entre 0 y 1
array_3 = np.random.random((3,5))
array_3 

array([[0.09926055, 0.52805369, 0.73722524, 0.37917445, 0.14059796],
       [0.94332383, 0.52187448, 0.45090885, 0.06713667, 0.9104307 ],
       [0.35068954, 0.90531516, 0.38173563, 0.34082004, 0.39697949]])

In [16]:
# Establecemos una semilla de numeros aleatorios, cada semilla tiene una secuencia de numeros aleatorios fijos ,
# por ello fijar una semillia hebita que la aleetoriedad se repita cambie

np.random.seed(30)

# Creamos un array de números aleatorios enntre 0 y 10 de tamaño (3,5)
array_4 =np.random.randint(0,10,(3,5))
array_4

array([[5, 5, 4, 7, 2],
       [5, 1, 3, 9, 7],
       [7, 1, 1, 3, 2]], dtype=int32)

In [17]:
# Encontramos todos los elementos unicos dentro de un array 
np.unique(array_4)

array([1, 2, 3, 4, 5, 7, 9], dtype=int32)

In [ ]:
# Extraer un elemento de un array 
array_4[1]

array([5, 1, 3, 9, 7], dtype=int32)

In [19]:
# Extraer las dos primeras filas de un array
array_4[:2]

array([[5, 5, 4, 7, 2],
       [5, 1, 3, 9, 7]], dtype=int32)

In [20]:
# Sí queremos extraer una cantindad determinad de elementos de una determinada cantidad de filas 
array_4[:2,:2]

array([[5, 5],
       [5, 1]], dtype=int32)

In [30]:
# Creamos 2 array de 3 filas por 4 columnas (3x4) relleno de numeros aleatorios y otro igual pero de puros numeros uno 

array_5 = np.random.randint(0,10,(3,4))
print(array_5)
print("")
array_6 =np.ones((3,4))
print(array_6)

[[4 2 6 2]
 [9 9 3 0]
 [8 9 2 1]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [31]:
# Sumamos los array
array_5 + array_6


array([[ 5.,  3.,  7.,  3.],
       [10., 10.,  4.,  1.],
       [ 9., 10.,  3.,  2.]])

In [ ]:
# Hacemos un array de 4 x 3 , es importante aclarar que no podemos hace operaciones entre arrays de diferentes dimensiones
array_7 = np.ones((4,3))
array_7

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Creamos 2 array nuevos para hacer multipliaciones 
array_8 = np.random.randint(1,10,(3,4))
array_9 = np.random.randint(1,10,(3,4))

# visualziamos el los array 
print(array_8)
print("")
print(array_9)
print("")

# Multiplicamos los array
x = array_8 * array_9

# Visualozamos el resultado 
print(x)


[[9 5 8 2]
 [1 7 6 2]
 [3 3 7 8]]

[[5 6 5 9]
 [6 5 7 1]
 [8 3 9 9]]

[[45 30 40 18]
 [ 6 35 42  2]
 [24  9 63 72]]


In [ ]:
# tambien podemos elevar algun array al cuadrado
array_8**2

array([[81, 25, 64,  4],
       [ 1, 49, 36,  4],
       [ 9,  9, 49, 64]], dtype=int32)

In [38]:
# Podemos sacar raiz cuadrada 
np.sqrt(array_9)

array([[2.23606798, 2.44948974, 2.23606798, 3.        ],
       [2.44948974, 2.23606798, 2.64575131, 1.        ],
       [2.82842712, 1.73205081, 3.        , 3.        ]])

In [39]:
# Podemos sacar el promedio de un array completo
array_9.mean()

np.float64(6.083333333333333)

In [41]:
# Podemos encontrar el valor maximo 
array_9.max()

np.int32(9)

In [42]:
# Podemos encontrar el valor minimo 
array_9.min()

np.int32(1)

In [46]:
# Podemos cambiar las dimenciones de nuestro array de un de 3 x 4 por uno de 12 x 1 
array_10 = array_9.reshape((12,1))
array_10

array([[5],
       [6],
       [5],
       [9],
       [6],
       [5],
       [7],
       [1],
       [8],
       [3],
       [9],
       [9]], dtype=int32)

In [47]:
# Podemos cambiar nuestro array de manera que las filas se vielvan columnas unsando "Transponer"
# No olvidar que estos siguine siendo de 2 dimenciones en el primero caso es de 12 x 1 y en este es de 1 x 12
array_10.T

array([[5, 6, 5, 9, 6, 5, 7, 1, 8, 3, 9, 9]], dtype=int32)

In [48]:
# Podmeos comparar arrays 
array_11 = array_8 > array_9
array_11

array([[ True, False,  True, False],
       [False,  True, False,  True],
       [False, False, False, False]])

In [ ]:
# Por hacer l aultima operacion los valores cambiaron su tipo de dato 
array_11.dtype

dtype('bool')

In [ ]:
# Podemos revisar si hay valores iguales
array_8 == array_9

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False]])

In [ ]:
# Podemos revisar si hay mauores o iguales
array_8 >= array_9

array([[ True, False,  True, False],
       [False,  True, False,  True],
       [False,  True, False, False]])

In [ ]:
# Podemos buscar si hay valores en un array mayores a 2, por ejemplo
array_9 > 2

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [ True,  True,  True,  True]])

In [ ]:
# Podemos ordenar de menor a mayor los elementos de un array eb cada linea. 
np.sort(array_9)

array([[5, 5, 6, 9],
       [1, 5, 6, 7],
       [3, 8, 9, 9]], dtype=int32)